kind: pipeline
name: frontend

steps:
  - name: build
    image: node
    commands:
      - npm ci
      - npm run build

  - name: test
    image: node
    commands:
      - npm ci
      - npm run test

  - name: dockerize
    image: plugins/docker
    settings:
      registry: git.codemonke.de
      repo: git.codemonke.de/invoice/invoice-gen
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: latest

  - name: notify
    image: appleboy/drone-discord
    settings:
      username: Ciboy
      avatar_url: https://cdn-icons-png.flaticon.com/256/4829/4829581.png
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
    message: '{{build.author}} pushed to {{build.branch}} ({{repo.name}})'
    when:
      status: [ success, failure ]
