kind: pipeline
name: frontend

environment:
  MAIL_HOST: cicd
  MAIL_PORT: 0cicd
  MAIL_USER: cicd
  MAIL_PASSWORD: cicd
  MAIL_FROM: cicd

steps:
  - name: build
    image: node
    commands:
      - npm ci
      - npm run build

  - name: test
    image: node
    commands:
      - npm ci
      - npm run test

  - name: docker
    image: plugins/docker
    settings:
      registry: git.codemonke.de
      repo: git.codemonke.de/invoice/invoice-gen
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags: latest
