/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddInvoiceRequest {
  positions: ({
    amount: number;
    description: string;
    price: number;
    unit: 'hours' | 'pieces';
  })[];
  projectId: number;
}

export interface DeleteInvoiceRequest {
  id: number;
}

export interface EditInvoiceRequest {
  addedPositions?: ({
    amount: number;
    description: string;
    price: number;
    unit: 'hours' | 'pieces';
  })[];
  deletedPositions?: number[];
  id: number;
  projectId?: number;
  updatedPositions?: ({
    amount?: number;
    description?: string;
    id: number;
    price?: number;
    unit?: 'hours' | 'pieces';
  })[];
}

export interface PublishInvoiceRequest {
  id: number;
}

export interface ShowInvoiceRequest {
  filename: string;
}
