/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddInvoiceRequest {
  positions: ({
    amount: number;
    description: string;
    price: number;
    unit: 'hours' | 'pieces';
  })[];
  projectId: number;
}

export interface DeleteInvoiceRequest {
  id: number;
}

export interface EditInvoiceRequest {
  deletedPositions?: number[];
  id: number;
  positions?: ({
    added?: boolean;
    amount?: number;
    description?: string;
    id: number;
    price?: number;
    unit?: 'hours' | 'pieces';
  })[];
  projectId?: number;
}

export interface PublishInvoiceRequest {
  id: number;
}
