/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface DeleteTimeTrackRequest {
  timeTrackId: number;
}

export interface EditTimeTrackRequest {
  description?: string;
  endDate?: Date;
  startDate?: Date;
  timeTrackId: number;
}

export interface StartTimeTrackRequest {
  projectId: number;
}

export interface StopTimeTrackRequest {
  description: string;
  timeTrackId: number;
}
